//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMB_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poliza
    {
        public long Pol_Numero_Poliza { get; set; }
        public int Tipo_Poliza_ID { get; set; }
        public int Aseguradora_ID { get; set; }
        public long Tomador_Documento { get; set; }
        public long Beneficiario_Documento { get; set; }
        public System.DateTime Pol_Vigencia_Inicial { get; set; }
        public System.DateTime Pol_Vigencia_Final { get; set; }
        public decimal Pol_Valor_Prima { get; set; }
        public string Pol_Estado { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
    
        public virtual Aseguradora Aseguradora { get; set; }
        public virtual Beneficiario Beneficiario { get; set; }
        public virtual Pol_veh_entity_framework Pol_veh_entity_framework { get; set; }
        public virtual Tipo_poliza Tipo_poliza { get; set; }
        public virtual Tomador Tomador { get; set; }
    }
}
