//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMB_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polizas_Vehiculos
    {
        public long PolVeh_Numero_Poliza { get; set; }
        public string PolVeh_Veh_Placa { get; set; }
        public System.DateTime Fecha_creacion { get; set; }
    
        public virtual Poliza Poliza { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
