//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMB_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tomador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tomador()
        {
            this.Poliza = new HashSet<Poliza>();
        }
    
        public long Tom_Documento { get; set; }
        public string Tom_Tip_Doc { get; set; }
        public string Tom_Nombres { get; set; }
        public string Tom_Apellidos { get; set; }
        public string Tom_Direccion { get; set; }
        public long Tom_Telefono { get; set; }
        public string Tom_Email { get; set; }
        public System.DateTime Tom_Fecha_Nacimiento { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Poliza> Poliza { get; set; }
    }
}
