//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMB_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public string Nombre_Usuario { get; set; }
        public string Contraseña_Usuario { get; set; }
        public string Email_Usuario { get; set; }
        public long Documento_Usuario { get; set; }
        public byte[] Imagenes_Usuario { get; set; }
        public System.DateTime Fecha_creacion { get; set; }
    }
}
