//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMB_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculo()
        {
            this.Pol_veh_entity_framework = new HashSet<Pol_veh_entity_framework>();
        }
    
        public string Veh_Placa { get; set; }
        public string Veh_Modelo { get; set; }
        public int Veh_Fasecolda { get; set; }
        public string Veh_Servicio { get; set; }
        public string Veh_Clase { get; set; }
        public string Veh_Marca { get; set; }
        public decimal Veh_Valor_Auto { get; set; }
        public System.DateTime Veh_Vigencia_Soat { get; set; }
        public string Veh_Soat_Estado { get; set; }
        public System.DateTime Fecha_creacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pol_veh_entity_framework> Pol_veh_entity_framework { get; set; }
    }
}
