//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMB_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vista_reporte_soat
    {
        public long Numero_de_poliza { get; set; }
        public string Tipo_de_Documento { get; set; }
        public Nullable<long> Documento { get; set; }
        public string Nombres { get; set; }
        public string Placa { get; set; }
        public Nullable<int> Fasecolda { get; set; }
        public string Servicio { get; set; }
        public string Clase { get; set; }
        public string Modelo { get; set; }
        public string Marca { get; set; }
        public string Valor_del_Auto { get; set; }
        public Nullable<System.DateTime> Vigencia_SOAT { get; set; }
        public string Estado_SOAT { get; set; }
    }
}
