//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMB_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vista_Ben_2
    {
        public long Documento { get; set; }
        public string Tipo_documento { get; set; }
        public string Nombres { get; set; }
        public System.DateTime Fecha_de_nacimiento { get; set; }
        public string Direccion { get; set; }
        public string Email { get; set; }
        public long Telefono { get; set; }
    }
}
