//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMB_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vista_Vig_Pol_2
    {
        public long Numero_Poliza { get; set; }
        public string Tipo_documento { get; set; }
        public string Nombres { get; set; }
        public long Telefono { get; set; }
        public string Valor_prima { get; set; }
        public System.DateTime VIgencia_Inicial { get; set; }
        public System.DateTime Vigencia_Final { get; set; }
        public string Estado { get; set; }
    }
}
