//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMB_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vista_reporte_vigencias
    {
        public long Numero_de_poliza { get; set; }
        public string Tipo_de_documento { get; set; }
        public Nullable<long> Documento { get; set; }
        public string Nombres_Tomador { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string Valor_prima { get; set; }
        public System.DateTime Vigencia_Inicial { get; set; }
        public System.DateTime Vigencia_Final { get; set; }
        public string Estado_de_la_poliza { get; set; }
    }
}
