//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMB_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vista_Vehiculos
    {
        public Nullable<long> Numero_de_Poliza { get; set; }
        public string Aseguradora { get; set; }
        public string Ramo { get; set; }
        public string Tipo_Documento_Tomador { get; set; }
        public Nullable<long> Documento_Tomador { get; set; }
        public string Nombres_Tomador { get; set; }
        public string Placa { get; set; }
        public int Fasecolda { get; set; }
        public string Clase { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Servicio { get; set; }
    }
}
