//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMB_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vista_Listado_Polizas
    {
        public long Numero_de_Poliza { get; set; }
        public string Ramo { get; set; }
        public string Nombre_Aseguradora { get; set; }
        public string Tipo_documento_Tomador { get; set; }
        public Nullable<long> Documento_Tomador { get; set; }
        public string Nombres_Tomador { get; set; }
        public string Tipo_documento_Beneficiario { get; set; }
        public Nullable<long> Documento_Beneficiario { get; set; }
        public string Nombres_Beneficiario { get; set; }
        public string Vigencia_Inicial { get; set; }
        public string Vigencia_Final { get; set; }
        public string Valor_Prima { get; set; }
        public string Estado { get; set; }
    }
}
